In [1]:
import pandas as pd

In [3]:
import pandas as pd

books= {
    "isbn": ["9780553386790"],
    "title": ["Dune"],
    "author": ["Frank Herbert"],
    "genre": ["Science Fiction"],
    "book_language": ["English"],
    "is_available": [True]
}

books_df = pd.DataFrame(books)

books_df

,isbn,title,author,genre,book_language,is_available
0,9780553386790,Dune,Frank Herbert,Science Fiction,English,True

In [4]:
users_data= {
    "user_name": ["David Miller"],
    "phone_number": ["9876543220"],
    "email": ["david.miller@gmail.com"],
    "max_loans": [5]
}

users_df = pd.DataFrame(users_data)

users_df

      user_name phone_number                   email  max_loans
0  David Miller   9876543220  david.miller@gmail.com          5

In [4]:
reservations_data = {
    "reservation_id": [11],
    "isbn": ["9780553386790"],
    "user_id": [2],
    "reservation_date": ["2026-09-14 10:00:00"],
    "ready_date": [None],
    "status": ["WAIT"]
}

reservations_df = pd.DataFrame(reservations_data)

reservations_df

,reservation_id,isbn,user_id,reservation_date,ready_date,status
0,11,9780553386790,2,2026-09-14 10:00:00,None,WAIT

In [ ]:
from dotenv import load_dotenv
import os

load_dotenv() # error if .env file is not found

False

In [5]:
from dotenv import load_dotenv
import os
from pathlib import Path

env_path = Path.cwd() / ".env"

print("Current folder:", Path.cwd())
print("Looking for:", env_path)
print("Exists:", env_path.exists())

load_dotenv(dotenv_path=env_path)

password = os.getenv("mysql_password")
print("Password loaded:", password is not None)

Current folder: c:\Users\shiva\Documents\Project\projects\library\notebooks
Looking for: c:\Users\shiva\Documents\Project\projects\library\notebooks\.env
Exists: True
Password loaded: True

In [6]:
schema = "library"
host = "127.0.0.1"
user = "root"
password = os.getenv("mysql_password")
port = 3306

connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

In [7]:
books_df

,isbn,title,author,genre,book_language,is_available
0,9780553386790,Dune,Frank Herbert,Science Fiction,English,True

In [8]:
books_df.columns

Index(['isbn', 'title', 'author', 'genre', 'book_language', 'is_available'], dtype='str')

In [9]:
print(connection_string)

mysql+pymysql://root:Shivalingappa123@127.0.0.1:3306/library

In [15]:
connection_string = "mysql+pymysql://root:YOUR_PASSWORD@localhost/library"

In [10]:
from sqlalchemy import create_engine

engine = create_engine(connection_string)

books_df.to_sql(
    "books",
    con=engine,
    if_exists="append",
    index=False
)

1

In [12]:
print(books_df.columns.tolist())

['isbn', 'title', 'author', 'genre', 'book_language', 'is_available']

In [14]:
books_df_from_sql = pd.read_sql("books",
                                 con = connection_string)
books_df_from_sql

,isbn,title,author,genre,book_language,is_available
0,9780061120084,To Kill a Mockingbird,Harper Lee,Classic,English,1
1,9780132350884,Clean Code,Robert C. Martin,Programming,English,1
2,9780140449136,The Odyssey,Homer,Epic,English,1
3,9780261103303,The Hobbit,J.R.R. Tolkien,Fantasy,English,1
4,9780439023481,The Hunger Games,Suzanne Collins,Science Fiction,English,1
5,9780451524935,1984,George Orwell,Dystopian,English,1
6,9780553386790,Dune,Frank Herbert,Science Fiction,English,1
7,9780743273565,The Great Gatsby,F. Scott Fitzgerald,Classic,English,1
8,9781491957660,Python Crash Course,Eric Matthes,Programming,English,1
9,9784062745000,Norwegian Wood,Haruki Murakami,Romance,Japanese,1
10,9788184001754,The Alchemist,Paulo Coelho,Adventure,English,1

In [15]:
users_df.to_sql(
    "users",
    con=engine,
    if_exists="append",
    index=False
)

1

In [16]:
print(users_df.columns.tolist())

['user_name', 'phone_number', 'email', 'max_loans']

In [17]:
users_df_from_sql = pd.read_sql("users",
                                 con = connection_string)
users_df_from_sql

,user_id,user_name,phone_number,email,max_loans
0,1,John Smith,9876543210,john.smith@gmail.com,5
1,2,Emma Johnson,9876543211,emma.johnson@gmail.com,5
2,3,Michael Brown,9876543212,michael.brown@gmail.com,3
3,4,Sophia Davis,9876543213,sophia.davis@gmail.com,5
4,5,Daniel Wilson,9876543214,daniel.wilson@gmail.com,4
5,6,Olivia Martinez,9876543215,olivia.martinez@gmail.com,5
6,7,James Anderson,9876543216,james.anderson@gmail.com,2
7,8,Ava Taylor,9876543217,ava.taylor@gmail.com,5
8,9,William Thomas,9876543218,william.thomas@gmail.com,3
9,10,Isabella Moore,9876543219,isabella.moore@gmail.com,5
10,21,David Miller,9876543220,david.miller@gmail.com,5

In [18]:
reservations_df_from_sql = pd.read_sql("reservations",
                                 con = connection_string)
reservations_df_from_sql

,reservation_id,isbn,user_id,reservation_date,ready_date,status
0,1,9780140449136,2,2026-09-08 10:00:00,NaT,WAIT
1,2,9780743273565,3,2026-09-08 11:30:00,NaT,WAIT
2,3,9780061120084,4,2026-09-08 12:00:00,2026-09-10 09:00:00,READY
3,4,9780451524935,5,2026-09-09 09:15:00,NaT,WAIT
4,5,9780261103303,6,2026-09-09 10:30:00,2026-09-11 14:00:00,READY
5,6,9780439023481,7,2026-09-09 13:00:00,NaT,WAIT
6,7,9780132350884,8,2026-09-10 09:45:00,NaT,CANCELLED
7,8,9781491957660,9,2026-09-10 11:00:00,2026-09-12 10:00:00,FULFILLED
8,9,9784062745000,10,2026-09-10 15:30:00,NaT,EXPIRED
9,10,9788184001754,1,2026-09-11 16:00:00,NaT,WAIT

In [19]:
loans_data = {
    "isbn": ["9780553386790"],
    "user_id": [2],
    "loan_date": ["2026-09-14"],
    "due_date": ["2026-09-28"],
    "extended_due_date": [None],
    "extension_count": [0],
    "late_fee": [0.00],
    "return_date": [None]
}

loans_df = pd.DataFrame(loans_data)

loans_df

,isbn,user_id,loan_date,due_date,extended_due_date,extension_count,late_fee,return_date
0,9780553386790,2,2026-09-14,2026-09-28,None,0,0.0,None

In [20]:
loans_df.to_sql(
    name="loans",
    con=engine,
    if_exists="append",
    index=False
)

1

In [21]:
loans_df_from_sql = pd.read_sql("loans",
                                 con = connection_string)
loans_df_from_sql

,loan_id,isbn,user_id,loan_date,due_date,extended_due_date,extension_count,late_fee,return_date
0,1,9780140449136,1,2026-09-01,2026-09-15,NaT,0,0.0,NaT
1,2,9780743273565,2,2026-09-02,2026-09-16,NaT,0,0.0,NaT
2,3,9780061120084,3,2026-08-20,2026-09-03,2026-09-10,1,2.5,NaT
3,4,9780451524935,4,2026-09-04,2026-09-18,NaT,0,0.0,NaT
4,5,9780261103303,5,2026-08-25,2026-09-08,NaT,0,5.0,NaT
5,6,9780439023481,6,2026-09-05,2026-09-19,NaT,0,0.0,NaT
6,7,9780132350884,7,2026-08-15,2026-08-29,NaT,0,10.0,2026-08-28
7,8,9781491957660,8,2026-09-06,2026-09-20,NaT,0,0.0,NaT
8,9,9784062745000,9,2026-08-10,2026-08-24,NaT,0,7.5,2026-08-23
9,10,9788184001754,10,2026-09-07,2026-09-21,NaT,0,0.0,NaT
10,11,9780553386790,2,2026-09-14,2026-09-28,NaT,0,0.0,NaT